In [1]:
%matplotlib inline

In [10]:
import pls_nipals
import pandas as pd
import numpy as np

In [45]:
from sklearn import linear_model
clf = linear_model.Lasso(alpha = 0.1)
### [[one array of genes per sample], []]
clf.fit([[0, 3, 3], [1, 1, 1]], [0, 10])
#Lasso(alpha=0.1, copy_X=True, fit_intercept=True, max_iter=1000,
#   normalize=False, positive=False, precompute=False, random_state=None,
#   selection='cyclic', tol=0.0001, warm_start=False)

clf.predict([[1, 1, 8]])
#array([ 0.8])

array([ 9.9])

In [34]:
clf.coef_

array([ 0. ,  0. , -0.4])

In [12]:
pd.DataFrame(np.array([[0, 0], [1, 1]]))#, [0, 1])

0  1
0  0  0
1  1  1